### ISSUE TITLE
Clean UP & Dockerization eos97yu

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos97yu#5]
Please check that the model is working and refactor it model to the latest eos-template structure.
The workflows have already been updated, you can start by checking if the Actions have run successfully or changes need to be made

**Comment by samuelmaina** [comment]
Hi @GemmaTuron, 
This https://github.com/ersilia-os/ersilia/issues/717#issuecomment-1606014574  error still persisted in local env. I read that the error is caused by having python 3.7 , the model was dumped using python 3.6. When I installed python 3.6 , I get this error, I am using `import joblib.` , I also have pulled the latest model joblib  using `git lfs pull` and have used the exact packages that were specified in the dockerfile. 
```
Traceback (most recent call last):
  File ".//code/main.py", line 28, in <module>
    outputs = my_model(smiles_list)
  File ".//code/main.py", line 18, in my_model
    return predict_LogPe(mols)
  File "/home/samuelmayna/ersilia_github_models/eos97yu/model/framework/code/predict.py", line 27, in predict_LogPe
    mdl = joblib.load(os.path.join(checkpoints_dir, "flaml.joblib"))
  File "/home/samuelmayna/miniconda3/envs/eos97yu/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/samuelmayna/miniconda3/envs/eos97yu/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/home/samuelmayna/miniconda3/envs/eos97yu/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 239
```

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 
Can you then try to run the model following the source code and the requirements there? that should help to identify the right version to unpickle the model.
Also, have you checked that the path is correct? always print it to be sure

**Comment by samuelmaina** [comment]
I have checked, the path is correct but there is no source code. The model had a paper and the training dataset with the params. The the code for training was done by @miquelduranfrigola , not sure about the training.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Indeed there is a training notebook which should run with the requirements specified in the DockerFile. There it indicates python 3.7. so why do you suggest the model was developed in Python 3.6?
When you first tried fetching the model from --repo_path, what was the log of the error, could you please share it?
If the --repo_path fails, then manually recreate the environment following the steps indicated in the Dockerfile and try to run the relevant files (either predict.py, main.py etc)
This model in particular already has a test csv on it

Please note that I  have updated the workflows so make sure to rebase your fork before committing any changes

**Comment by samuelmaina** [comment]
@GemmaTuron , I run the model and I got this errors 
[eos97yu_cli_fetch_prev.log](https://github.com/ersilia-os/eos97yu/files/11877185/eos97yu_cli_fetch_prev.log)
. I then downloaded the model a new and only changed the docker file to install install rdkit with pip. I made changes progressively while making sure everything was working fine.
.Every smiles has an output 
   - [eos97yu_cli_fetch.log](https://github.com/ersilia-os/eos97yu/files/11877211/eos97yu_cli_fetch.log)
   - [eos97yu_cli_eml_predict.csv](https://github.com/ersilia-os/eos97yu/files/11877212/eos97yu_cli_eml_predict.csv)
  
I have opened a PR.

**Comment by GemmaTuron** [comment]
@samuelmaina 
I see the training is now repeated.
Please leave the training folder only under one single location. Also, the .gitattributes file is not needed, since the model is small enough (less than 50 mb) also, it is currently tracking pkl files, which are nto existing in the repo.
amend and open a new PR

**Comment by samuelmaina** [comment]
@GemmaTuron , I  have  made a new PR.
